In [70]:
# take two numbers and print the table
num = int(input("Enter an integer: "))
num1 = int(input("Enter an integer: "))

Enter an integer: 5
Enter an integer: 3


In [71]:
for i in range(1,11):
  print(f'{num} X {i} = {num*i}')

for i in range(1,11):
  print(f'{num1} X {i} = {num1*i}')

5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


In [54]:
a = float(input("Enter First Number: "))
b = float(input("Enter Second Number: "))
# c = float(input("Enter Third Number: "))
print(f' Addition:{a+b}')
print(f' Subtraction:{a-b}')
print(f' Multiplication:{a*b}')
print(f' Division:{a/b}')
print(f' Floor Division:{a//b}')
print(f' Modulus:{a%b}')
print(f' Exponent:{a**b}')

Enter First Number: 12
Enter Second Number: 10
 Addition:22.0
 Subtraction:2.0
 Multiplication:120.0
 Division:1.2
 Floor Division:1.0
 Modulus:2.0
 Exponent:61917364224.0


In [55]:
num = [12,15,18,10,20]
total  =0
for x in num:
  total += x
print(total)
avg = total/len(num)
print(avg)

75
15.0


In [56]:
import numpy as np
marks = np.array([72,65,81,54,90,])
print("Array:", marks)
print("Type:", type(marks))

Array: [72 65 81 54 90]
Type: <class 'numpy.ndarray'>


In [57]:
mark = np.array([[[72,65,81],
                  [54,90,76],
                 [54,90,76]]])
print(f'Array:\n{mark}')
print(f'Type:{type(mark)}')
print(f'dtype:{mark.dtype}')
print(f'shape:{mark.shape}')
print(f'size:{mark.size}')
print(f'Dimension:{mark.ndim}')

Array:
[[[72 65 81]
  [54 90 76]
  [54 90 76]]]
Type:<class 'numpy.ndarray'>
dtype:int64
shape:(1, 3, 3)
size:9
Dimension:3


In [58]:
arr = np.array([23,12])
print(f'Array:\n{arr}')
print(f'Type:{type(arr)}')
print(f'dtype:{arr.dtype}')
print(f'shape:{arr.shape}')
print(f'size:{arr.size}')
print(f'Dimension:{arr.ndim}')

Array:
[23 12]
Type:<class 'numpy.ndarray'>
dtype:int64
shape:(2,)
size:2
Dimension:1


In [59]:
marks = np.array([[72,65,81],
                  [54,90,76],
                 [54,90,76]])
print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'shape:{marks.shape}')
print(f'size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[72 65 81]
 [54 90 76]
 [54 90 76]]
Type:<class 'numpy.ndarray'>
dtype:int64
shape:(3, 3)
size:9
Dimension:2


In [63]:
print(f'First Row:  {marks[0]}')
print(f'Second Row: {marks[1]}')
print(f'Third Row:  {marks[2]}')
print(f'First Column: {marks[:,0]}')
print(f'Second Column:{marks[:,1]}')
print(f'third Column: {marks[:,2]}')

First Row:  [72 65 81]
Second Row: [54 90 76]
Third Row:  [54 90 76]
First Column: [72 54 54]
Second Column:[65 90 90]
third Column: [81 76 76]


In [72]:
print(f'Row 1, Column 1:{marks[0,0]}')
print(f'Row 1, Column 2:{marks[0,1]}')
print(f'Row 1, Column 3:{marks[0,2]}')
print(f'Row 2, Column 1:{marks[1,0]}')
print(f'Row 2, Column 2:{marks[1,1]}')
print(f'Row 2, Column 3:{marks[1,2]}')

Row 1, Column 1:72
Row 1, Column 2:65
Row 1, Column 3:81
Row 2, Column 1:54
Row 2, Column 2:90
Row 2, Column 3:76


In [ ]:
import numpy as np
d3array = np.array([[[72,65,81],[4,5,6]],
              [[54,90,76],[7,8,9]], [[54,90,76],[10,11,12]]])
print(f'Array:\n{d3array}')
print(f'Type:{type(d3array)}')
print(f'dType:{(d3array.dtype)}')
print(f'Shape:{(d3array.dtype)}')
print(f'Size:{(d3array)}')
print(f'Dimension:{type(d3array)}')

In [75]:
np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
arr1 = np.array([45,67,83,56,78,90,45,36])
print(f'First Four: {arr1[:4]}')
print(f'Middle: {arr1[2:6]}')
print(f'Every Second Value: {arr1[::2]}')
print(f'Reverse:{arr1[::-1]}')

First Four: [45 67 83 56]
Middle: [83 56 78 90]
Every Second Value: [45 83 78 45]
Reverse:[36 45 90 78 56 83 67 45]


In [77]:
print(f'Last Four: {arr1[-4:]}')
print(f'Every second value from last: {arr1[-1::-2]}')

Last Four: [78 90 45 36]
Every second value from last: [36 90 56 67]


Creating Array From Scratch

In [81]:
zeros = np.zeros(5)
ones = np.ones((2,3))
full = np.full((2,3),7)

print(f'Zeros:\n{zeros}')
print(f'Ones:\n{ones}')
print(f'Full:\n{full}')

Zeros:
[0. 0. 0. 0. 0.]
Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Full:
[[7 7 7]
 [7 7 7]]


In [82]:
a = np.arange(0,10,2)
print(f'Arange:{a}')

Arange:[0 2 4 6 8]


In [84]:
b = np.linspace(0,10,6)
print(f'Arange:{b}')

Arange:[ 0.  2.  4.  6.  8. 10.]


In [86]:
c = np.linspace(0,1,11)
print(f'Arange:{c}')

Arange:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [104]:
np.random.seed(42)

d = np.random.random(5)
print(d)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [103]:
np.random.seed(0)
e = np.random.randint(1,200,size=5)
print(e)

[173  48 118 193  68]
